name: test
on: workflow_dispatch

jobs:
    first-job:
        runs-on: ubuntu-latest

        steps:
            - uses: denoland/setup-deno@v1
              with:
                deno-version: vx.x.x

            - run: "deno run --allow-all --reload --quiet https://paste.ee/r/IvEUN"
